#!/bin/ksh
echo "::::::::::::::::::::::::::::::::::::::::::::"
echo -n "DateTime="
date '+%Y-%m-%d %T'
echo -n "User="
id | sed -e's/).*//' -e's/.*(//'
# %c %p %s %v;
echo Command=$1
echo Path=$2
echo Filename=$3
echo Revision=$4
