#!/bin/ksh

date=$(date '+%Y%m%d-%H%M%S')
day=${date%-*}
logfile="/home/cvs/logs/commitlog.$day"
if [[ ! -e "$logfile" ]]; then
 touch $logfile
 chmod 666 $logfile
fi
for redirect in here; do
  echo "DateTime=$date"
  echo -n "User="
  id | sed -e's/).*//' -e's/.*(//'
	# %c %p %s %v;
  echo Command=$1; shift
  echo Path=$1; shift
  while [[ $# -gt 0 ]]; do
    echo Filename=$1; shift
    echo Revision=$1; shift
  done
  cat
  echo "::::::::::::::::::::::::::::::::::::::::::::"
done >> $logfile
