/* A polyfill for browsers that don't support ligatures. */
/* The script tag referring to this file must be placed before the ending body tag. */

/* To provide support for elements dynamically added, this script adds
   method 'icomoonLiga' to the window object. You can pass element references to this method.
*/
(function () {
    'use strict';
    function supportsProperty(p) {
        var prefixes = ['Webkit', 'Moz', 'O', 'ms'],
            i,
            div = document.createElement('div'),
            ret = p in div.style;
        if (!ret) {
            p = p.charAt(0).toUpperCase() + p.substr(1);
            for (i = 0; i < prefixes.length; i += 1) {
                ret = prefixes[i] + p in div.style;
                if (ret) {
                    break;
                }
            }
        }
        return ret;
    }
    var icons;
    if (!supportsProperty('fontFeatureSettings')) {
        icons = {
            'allmfdtools-bv-flatten-view': '&#xe957;',
            'alpha-datatype-derived-v2': '&#xeaf8;',
            'alpha-datatype-key-v2': '&#xeafd;',
            'analytic-functions-advanced': '&#xeb00;',
            'change-source': '&#xeb02;',
            'change-target': '&#xeb03;',
            'data-except-all2': '&#xeb06;',
            'data-file': '&#xeb07;',
            'data-intersect-all2': '&#xeb08;',
            'data-union-all2': '&#xeb09;',
            'database-automap': '&#xeb0d;',
            'database-join': '&#xeb0e;',
            'database-source-keyed': '&#xeb0f;',
            'database-source': '&#xeb10;',
            'database-target-new-keyed': '&#xeb12;',
            'database-target-new': '&#xeb13;',
            'database-view-joins': '&#xeb14;',
            'datatype-date-key': '&#xeb1a;',
            'datatype-geo-derived': '&#xeb1b;',
            'datatype-geo-key': '&#xeb1c;',
            'datatype-time-derived': '&#xeb1d;',
            'datatype-timestamp-derived': '&#xeb1f;',
            'datatype-timestamp-key': '&#xeb20;',
            'decompose_date': '&#xeb21;',
            'dmc-from-data-source-keyed': '&#xeb26;',
            'dmc-rom-data-source': '&#xeb27;',
            'dmc-sql-fltr-and-fltrd-data': '&#xeb29;',
            'dmc-sql-fltr-srtd-fltrd-data': '&#xeb2a;',
            'dmc-sql-gear': '&#xeb2b;',
            'dmc-sql-sorted': '&#xeb2c;',
            'dmc-sql-srtd-fltrd-data': '&#xeb2d;',
            'dmc-sql-with-filter-sorted': '&#xeb32;',
            'editor-foldlines': '&#xeb34;',
            'filtered-data': '&#xeb35;',
            'from-data-source': '&#xeb36;',
            'join-profiler': '&#xeb37;',
            'numeric-datatype-decimal-derived-v2': '&#xeb38;',
            'numeric-datatype-decimal-hash': '&#xeb39;',
            'numeric-datatype-decimal-key-hash': '&#xeb3a;',
            'numeric-datatype-decimal-key-v2': '&#xeb3b;',
            'numeric-datatype-derived-v2': '&#xeb3c;',
            'numeric-datatype-key-hash': '&#xeb3d;',
            'numeric-datatype-key-v2': '&#xeb46;',
            'parameters-add-default-parm': '&#xeb47;',
            'parameters-add-set-parm': '&#xeb48;',
            'parameters-edit-set-parm': '&#xeb49;',
            'sql-filtered-data': '&#xeb4a;',
            'sql-gear': '&#xeb4b;',
            'sql-sorted': '&#xeb4c;',
            'sql-with-filter-and-filtered-data': '&#xeb4d;',
            'sql-with-filter-and-sorted-filtered-data': '&#xeb4e;',
            'sql-with-filter-sorted': '&#xeb4f;',
            'sql-with-filter': '&#xeb50;',
            'sql-with-sorted-filtered-data': '&#xeb51;',
            'start-email-and-scheduler': '&#xeb52;',
            'start-email': '&#xeb53;',
            'start-procedure-flow': '&#xeb54;',
            'start-scheduler': '&#xeb5d;',
            'target-transformations': '&#xeb5e;',
            'use-data': '&#xeb5f;',
            'wc-dt-database-add': '&#xeb60;',
            'wc-dt-join-add': '&#xeb61;',
            'wc-dt-join-remove': '&#xeb62;',
            'wc-dt-join': '&#xeb63;',
            'wc-dt-tree-remove': '&#xeb64;',
            'layers-geographic': '&#xeb65;',
            'invert-case': '&#xeb66;',
            'format-conversion': '&#xeb67;',
            'manage-sql-repository': '&#xeb68;',
            'measure-rulers-cascaded': '&#xeb69;',
            'mfd-bv-flatten-view': '&#xeb6a;',
            'migration': '&#xeb6b;',
            'object-caption': '&#xeb6c;',
            'procedure-flow-scheduled': '&#xeb6d;',
            'remove-from-hierarchy': '&#xeb6e;',
            'replace': '&#xeb6f;',
            'repository-management': '&#xeb70;',
            'task-email': '&#xeb71;',
            'variable-size-large': '&#xeb72;',
            'variable-size-small': '&#xeb72;',
            'variable-size-medium': '&#xeb72;',
            'wc-dbms-prerequisites': '&#xeb73;',
            'where-total': '&#xeb74;',
            'write-in-calender': '&#xeb75;',
            'flow-procedure-c': '&#xeb76;',
            'flow-procedure-cc': '&#xeb77;',
            'flow-procedure-directload-d': '&#xeb78;',
            'flow-procedure-directload-file-export': '&#xeb79;',
            'flow-procedure-directload-star': '&#xeb7a;',
            'flow-procedure-q': '&#xeb7b;',
            'flow-procedure-qc': '&#xeb7c;',
            'cascaded-windows': '&#xeb7d;',
            'time-dimension': '&#xeb7e;',
            'timestamp': '&#xeb7f;',
            'focexec-procedure-scheduled': '&#xeb80;',
            'flow-procedure-scheduled': '&#xeb81;',
            'fex-procedure-scheduled': '&#xeb82;',
            'workspace-cogs': '&#xeb83;',
            'dimension-square-shadowed': '&#xeb84;',
            'dimension-square': '&#xeb85;',
            'folder-closed-delete-outline': '&#xeb86;',
            'folder-closed-outline': '&#xeb87;',
            'folder-minus-outline': '&#xeb88;',
            'page-with-check': '&#xeb89;',
            'page-with-plus-sign': '&#xeb8a;',
            'page-with-times-sign': '&#xeb8b;',
            'set-options-and-run': '&#xeb8c;',
            'resource-management': '&#xeb8d;',
            'find-next': '&#xeb8e;',
            'find-previous': '&#xeb8f;',
            'geomarker-check': '&#xeb90;',
            'geomarker-delete': '&#xeb91;',
            'geomarker-edit': '&#xeb92;',
            'geomarker-exclamation': '&#xeb93;',
            'geomarker-minus': '&#xeb94;',
            'flow-procedure': '&#xeb95;',
            'dmc': '&#xeb96;',
            'direct-load-flow': '&#xeb97;',
            'sql-box': '&#xeb98;',
            'dmc-sql-basic': '&#xeb99;',
            'dimension-square-hollow2': '&#xeb9a;',
            'dimension-square-hollow1': '&#xeb9b;',
            'dimension-numeric-decimal-2': '&#xeb9c;',
            'dimension-numeric-2': '&#xeb9d;',
            'dimension-alpha-2': '&#xeb9e;',
            'bulb-exclamation-mark': '&#xeb9f;',
            'analytic-functions': '&#xeba0;',
            'rm-reconfigure': '&#xeb3e;',
            'row-total': '&#xeb3f;',
            'scheduled-listener-job': '&#xeb40;',
            'sidebar-close': '&#xeb41;',
            'sidebar-open': '&#xeb42;',
            'snowflake': '&#xeb43;',
            'tab-navigate-mode-off': '&#xeb44;',
            'tab-navigate-mode-on': '&#xeb45;',
            'low-procedure-square-scheduled': '&#xeb55;',
            'flow-procedure-square-startflow': '&#xeb56;',
            'flow-procedure-square': '&#xeb57;',
            'data-except': '&#xeb58;',
            'data-intersect': '&#xeb59;',
            'dbms-passthrough': '&#xeb5a;',
            'fex-scheduled': '&#xeb5b;',
            'fex-start': '&#xeb5c;',
            'folder-open-outline': '&#xeb2e;',
            'folder-plus-outline': '&#xeb2f;',
            'folders-closed-outline': '&#xeb30;',
            'question-markin-square': '&#xeb0b;',
            'wc-connector-logo-raw-data-file': '&#xeafe;',
            'table-2x2-outline': '&#xeaff;',
            'procedure-flow': '&#xeb0a;',
            'mathsymbol-function': '&#xeb05;',
            'geomarker-plus-outline': '&#xeb15;',
            'geomarker-plus': '&#xeb16;',
            'geomarker-question': '&#xeb17;',
            'source-control': '&#xeafb;',
            'etl-custom-copy': '&#xeb18;',
            'profile-count': '&#xeb0c;',
            'literal-constant': '&#xeb01;',
            'flow-direct-load-procedure': '&#xeafc;',
            'fex-procedure': '&#xeade;',
            'focexec-procedure': '&#xeade;',
            'script-procedure': '&#xeade;',
            'variable': '&#xeadb;',
            'etl-parallel-job': '&#xeadd;',
            'triple-cube-frame': '&#xead9;',
            'connection-data-wizard': '&#xeab2;',
            'etl-copy-wizard': '&#xeab2;',
            'computer-tablet': '&#xea45;',
            'browser-session': '&#xea79;',
            'windows-command-line-session': '&#xeabb;',
            'search-file': '&#xe900;',
            'wc-dt-search': '&#xe900;',
            'bulb-lit-up': '&#xe901;',
            'wallet-outline': '&#xe909;',
            'data-access': '&#xe90e;',
            'security-shield-checked': '&#xeb04;',
            'security-shield-plain': '&#xe910;',
            'disabled': '&#xe914;',
            'need-value': '&#xe916;',
            'measure-disc': '&#xe926;',
            'measure-disc1': '&#xe926;',
            'measure-disc2': '&#xe926;',
            'single-cube-frame': '&#xe927;',
            'ibi-mfd': '&#xe92f;',
            'parent-children-hierarchy': '&#xe92f;',
            'wc-dt-tree': '&#xe930;',
            'diagnostic-stethoscope': '&#xe933;',
            'wc-connector-verify': '&#xe931;',
            'test-ok': '&#xe931;',
            'test': '&#xe931;',
            'test-fail': '&#xe932;',
            'wc-dt-bulk-load-verify': '&#xe934;',
            'wc-connector-bulk-load-verify': '&#xe934;',
            'wc-dt-case-sensitivity-verify': '&#xe935;',
            'wc-connector-case-sensitivity-verify': '&#xe935;',
            'report-line-chart': '&#xe937;',
            'thought-bubble': '&#xe943;',
            'folder-closed-solid': '&#xe949;',
            'folder-open-solid': '&#xe94a;',
            'folders-closed-solid': '&#xe948;',
            'generic-key': '&#xe94f;',
            'measure-disc1-hollow': '&#xe92e;',
            'measure-disc2-hollow': '&#xe92e;',
            'dimension-square-hollow-shadowed': '&#xe952;',
            'dimension-square-hollow': '&#xe953;',
            'add-all': '&#xe954;',
            'arrow-top-down': '&#xe955;',
            'arrow-bottom-up': '&#xe956;',
            'arrow-bottom-up-bold': '&#xe956;',
            'table-3x3-outline': '&#xeabd;',
            'graph-scatter-diagram': '&#xe95d;',
            'boxplot': '&#xe95f;',
            'procedure-test-query': '&#xe963;',
            'ib-full-logo': '&#xe965;',
            'ib-social-media-webicon': '&#xe967;',
            'dimension-abc': '&#xe96a;',
            'dimension-numeric': '&#xe96c;',
            'enabled': '&#xe97d;',
            'folder-plus-solid': '&#xe98c;',
            'new-item': '&#xe98c;',
            'lesser-or-equal': '&#xe990;',
            'greater-or-equal': '&#xe98d;',
            'folder-minus-solid': '&#xe993;',
            'adjust-function': '&#xe991;',
            'mathsymbol-function-x': '&#xe991;',
            'wc-dt-setting': '&#xe996;',
            'menu-item-drilldown': '&#xe99c;',
            'edit-object': '&#xe9aa;',
            'folder-closed-delete-solid': '&#xe9ab;',
            'geomarker': '&#xe9bb;',
            'dimension-geolocation': '&#xe9be;',
            'layers': '&#xeaca;',
            'measure-ruler-single': '&#xe9d0;',
            'column-group': '&#xe9d7;',
            'set-of-books': '&#xe9e0;',
            'wc-dt-mdf-flatten-view': '&#xe9ec;',
            'filetype-unassigned': '&#xea16;',
            'filetype-html': '&#xeafa;',
            'filetype-r': '&#xea07;',
            'filetype-unknown': '&#xea1a;',
            'filetype-json': '&#xe9fb;',
            'filetype-html5': '&#xea19;',
            'filetype-txt': '&#xe9ed;',
            'filetype-java': '&#xe9f5;',
            'file-filter2': '&#xea18;',
            'ibi-master': '&#xe9f6;',
            'filetype-excel-icon': '&#xea1b;',
            'filetype-excel': '&#xea1b;',
            'filetype-xlsx': '&#xea1b;',
            'filetype-ppt': '&#xe9f4;',
            'filetype-xml': '&#xe9f0;',
            'filetype-js': '&#xe9f1;',
            'filetype-shx': '&#xe9f2;',
            'filetype-mas': '&#xe9f3;',
            'filetype-sql': '&#xe9f7;',
            'filetype-tar': '&#xe9f9;',
            'filetype-zip': '&#xe9fa;',
            'filetype-dbf': '&#xe9fc;',
            'filetype-foc': '&#xe9fd;',
            'filetype-ftm': '&#xe9fe;',
            'filetype-jpeg': '&#xea17;',
            'filetype-jpg': '&#xea17;',
            'filetype-png': '&#xea1d;',
            'filetype-psd': '&#xe9ff;',
            'filetype-gif': '&#xea00;',
            'filetype-bmp': '&#xea08;',
            'filetype-tsv': '&#xea01;',
            'filetype-bak': '&#xea02;',
            'filetype-csv-plus': '&#xea04;',
            'filetype-csv': '&#xea04;',
            'filetype-sty': '&#xea06;',
            'filetype-rdata': '&#xea09;',
            'filetype-dat': '&#xea0b;',
            'filetype-svg': '&#xea0c;',
            'filetype-css': '&#xea0d;',
            'filetype-xsd': '&#xea0e;',
            'filetype-prj': '&#xea10;',
            'filetype-pdf': '&#xea11;',
            'filetype-log': '&#xea12;',
            'filetype-hti': '&#xea13;',
            'filetype-tro': '&#xea14;',
            'filetype-acx': '&#xea15;',
            'filetype-shp': '&#xea1c;',
            'uppercase': '&#xe975;',
            'touppercase': '&#xe975;',
            'lowercase': '&#xea3c;',
            'tolowercase': '&#xea3c;',
            'file-filter': '&#xea40;',
            'disk-file-save': '&#xea46;',
            'disk-file-save-as': '&#xea3a;',
            'disk-file-save-all': '&#xea44;',
            'target-data-source': '&#xea47;',
            'wc-dt-database': '&#xea49;',
            'disable-trace': '&#xea4e;',
            'stop-octagon-outline': '&#xeb31;',
            'stop-octagon-solid': '&#xea4f;',
            'signal-bars-1': '&#xea50;',
            'signal-bars-2': '&#xea51;',
            'signal-bars-3': '&#xea51;',
            'signal-bars-4': '&#xea51;',
            'signal-bars-5': '&#xea52;',
            'help-question-mark': '&#xea54;',
            'maintenance': '&#xea59;',
            'configuration': '&#xea5a;',
            'repeat-process': '&#xea61;',
            'goto-end': '&#xea69;',
            'goto-bottom': '&#xeb22;',
            'goto-top': '&#xeb23;',
            'goto_end': '&#xeb24;',
            'goto_start': '&#xeb25;',
            'goto-next-down': '&#xea73;',
            'goto-next-up': '&#xea74;',
            'goto-previous-left': '&#xea76;',
            'data-join-innerjoin2': '&#xea84;',
            'data-join-crossjoin': '&#xeacb;',
            'data-join-fulljoin2': '&#xea85;',
            'union': '&#xea85;',
            'data-join-rightjoin2': '&#xea86;',
            'data-join-leftjoin2': '&#xea88;',
          '0': 0
        };
        delete icons['0'];
        window.icomoonLiga = function (els) {
            var classes,
                el,
                i,
                innerHTML,
                key;
            els = els || document.getElementsByTagName('*');
            if (!els.length) {
                els = [els];
            }
            for (i = 0; ; i += 1) {
                el = els[i];
                if (!el) {
                    break;
                }
                classes = el.className;
                if (/ds-icon-/.test(classes)) {
                    innerHTML = el.innerHTML;
                    if (innerHTML && innerHTML.length > 1) {
                        for (key in icons) {
                            if (icons.hasOwnProperty(key)) {
                                innerHTML = innerHTML.replace(new RegExp(key, 'g'), icons[key]);
                            }
                        }
                        el.innerHTML = innerHTML;
                    }
                }
            }
        };
        window.icomoonLiga();
    }
}());
